<?php
require_once 'HTML/Template/PHPLIB/Helper.php';

/**
 * Test class for HTML_Template_PHPLIB_Helper.
 * Generated by PHPUnit on 2007-10-03 at 23:46:21.
 */
class HTML_Template_PHPLIB_HelperTest extends PHPUnit_Framework_TestCase {
    /**
     */
    public function testGetLines() {
        //test content
        $strContent = <<<EOT
1
22
333
44
5
EOT;
        $this->assertEquals(
            array('1', '22', '333', '44', '5'),
            HTML_Template_PHPLIB_Helper::getLines(null, $strContent)
        );

        //TODO: test file loading
    }

    /**
     */
    public function testSplitLines() {
        $strContent = <<<EOT
1
22
333
44
5
EOT;
        $this->assertEquals(
            array('1', '22', '333', '44', '5'),
            HTML_Template_PHPLIB_Helper::splitLines($strContent)
        );
    }
}
?>
